# Generated by Django 2.2.15 on 2022-09-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id_empleados', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('nombre_empresa', models.CharField(max_length=45)),
                ('fecha_creacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id_empresas', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('nit', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('sector', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('fecha_creado', models.DateField()),
                ('id_empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appempresa.empleados')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appempresa.roles')),
            ],
        ),
        migrations.CreateModel(
            name='transacciones',
            fields=[
                ('id_transaccion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('concepto', models.CharField(max_length=45)),
                ('monto', models.IntegerField()),
                ('tipo_transaccion', models.CharField(max_length=45)),
                ('usuario_id', models.CharField(max_length=45)),
                ('empresas_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appempresa.empresas')),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='id_usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appempresa.usuarios'),
        ),
    ]
